### ISSUE TITLE
Convert Mp4 Video To Mp3 Audio 

### ISSUE THREAD

**Issue by Shahzeb-A** [Shahzeb-A/Python-Automation-Scripts#4]
### Program Details

This program would allow user to select any **Mp4 video and convert it to Mp3 audio**.
User can also save the mp3 audio to **anywhere on the local system**. 

### Requirements
GUI and any other library that does the work

### Instructions
- Create a new folder for your script named 'Convert Mp4 Video To Mp3 Audio ' and put solution.py in it.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- Python

**Comment by hemantwasthere** [comment]
Hey @Shahzeb-A ,  I would like to work on this issue

**Comment by Shahzeb-A** [comment]
Hey @hemantwasthere , Sure, I'm assigning you.
